/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounting-accounts-account-types-id-account-type-detail': RouteRecordInfo<'accounting-accounts-account-types-id-account-type-detail', '/accounting/accounts/accountTypes/:id/accountTypeDetail', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-accounts-account-types-account-type-list': RouteRecordInfo<'accounting-accounts-account-types-account-type-list', '/accounting/accounts/accountTypes/accountTypeList', Record<never, never>, Record<never, never>>,
    'accounting-accounts-detail-account': RouteRecordInfo<'accounting-accounts-detail-account', '/accounting/accounts/detailAccount', Record<never, never>, Record<never, never>>,
    'accounting-accounts-detail-account-id-edit': RouteRecordInfo<'accounting-accounts-detail-account-id-edit', '/accounting/accounts/detailAccount/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-accounts-detail-account-create': RouteRecordInfo<'accounting-accounts-detail-account-create', '/accounting/accounts/detailAccount/create', Record<never, never>, Record<never, never>>,
    'accounting-accounts-detail-account-type': RouteRecordInfo<'accounting-accounts-detail-account-type', '/accounting/accounts/detailAccountType', Record<never, never>, Record<never, never>>,
    'accounting-accounts-detail-account-type-id-edit': RouteRecordInfo<'accounting-accounts-detail-account-type-id-edit', '/accounting/accounts/detailAccountType/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-accounts-detail-account-type-create': RouteRecordInfo<'accounting-accounts-detail-account-type-create', '/accounting/accounts/detailAccountType/create', Record<never, never>, Record<never, never>>,
    'accounting-accounts-general-ledger': RouteRecordInfo<'accounting-accounts-general-ledger', '/accounting/accounts/general-ledger', Record<never, never>, Record<never, never>>,
    'accounting-accounts-sub-ledger': RouteRecordInfo<'accounting-accounts-sub-ledger', '/accounting/accounts/sub-ledger', Record<never, never>, Record<never, never>>,
    'accounting-accounts-sub-ledger-id-edit': RouteRecordInfo<'accounting-accounts-sub-ledger-id-edit', '/accounting/accounts/sub-ledger/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accounting-accounts-sub-ledger-create': RouteRecordInfo<'accounting-accounts-sub-ledger-create', '/accounting/accounts/sub-ledger/create', Record<never, never>, Record<never, never>>,
    'accounting-accounts-sub-ledger-detail-type-link': RouteRecordInfo<'accounting-accounts-sub-ledger-detail-type-link', '/accounting/accounts/subLedger-DetailTypeLink', Record<never, never>, Record<never, never>>,
    'accounting-accounts-sub-ledger-detail-type-link-create': RouteRecordInfo<'accounting-accounts-sub-ledger-detail-type-link-create', '/accounting/accounts/subLedger-DetailTypeLink/create', Record<never, never>, Record<never, never>>,
    'accounting-journals-entries': RouteRecordInfo<'accounting-journals-entries', '/accounting/journals/entries', Record<never, never>, Record<never, never>>,
    'accounting-journals-entries-create': RouteRecordInfo<'accounting-journals-entries-create', '/accounting/journals/entries/create', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'rbac-permissions': RouteRecordInfo<'rbac-permissions', '/rbac/permissions', Record<never, never>, Record<never, never>>,
    'rbac-permissions-create': RouteRecordInfo<'rbac-permissions-create', '/rbac/permissions/create', Record<never, never>, Record<never, never>>,
    'rbac-roles': RouteRecordInfo<'rbac-roles', '/rbac/roles', Record<never, never>, Record<never, never>>,
    'rbac-roles-create': RouteRecordInfo<'rbac-roles-create', '/rbac/roles/create', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
